### ISSUE TITLE
Full Install isn't working - ftp isn't working?

### ISSUE THREAD

**Issue by f31n** [hangar18cc/mbzdb#6]
Logging into MusicBrainz FTP (ftp.musicbrainz.org)...
The latest is mbdump is ''
Mon Sep  5 18:33:19 2016: Downloading mbdump-cover-art-archive.tar.bz2... Unable to download file mbdump-cover-art-archive.tar.bz2: Illegal PORT command.

option 10 delivers the same error

**Comment by hectoras** [comment]
It is working for me, probably it was a temporary MusicBrainz FTP failure.

> hector@sirius:/mnt/ssd/mbzdb$ ./init.pl --action=10 --ask=0
> Using compress program null
> mbzdb v7.0 (2015-10-17)
> 
> Action selected using command line args: 10
> Running action: 10
> Continue? [y/n]Assuming 'yes'Logging into MusicBrainz FTP (ftp.musicbrainz.org)...
> The latest is mbdump is '20160727-001648'
> Thu Sep  8 14:35:45 2016: Downloading mbdump-cover-art-archive.tar.bz2... Done
> Thu Sep  8 14:36:00 2016: Downloading mbdump-stats.tar.bz2... Done
> Thu Sep  8 14:36:16 2016: Downloading mbdump-derived.tar.bz2... Done
> Thu Sep  8 14:37:01 2016: Downloading mbdump.tar.bz2... Done
> hector@sirius:/mnt/ssd/mbzdb$

**Comment by f31n** [comment]
the solution for me was turning on passive mode to do so i added another line at line 414 in src/functions.pl
$ftp->passive(on) or die "Can't put FTP host in passive mode: $!";

i'll update it here as well

best regards.
